version: "3"

services:
  app:
    image: golang:1.19
    volumes:
      - .:/app
    working_dir: /app
    command: "go run cmd/cli/"
  test:
    image: henri9813/golang-test:1.19
    volumes:
      - ./:/code
    working_dir: /code
